language: node_js
node_js:
  - 10.16.3
install:
  - nvm install node
  - node -v  
  - npm i -g yarn  
  - yarn  
  - npm install --save-dev jest
  - npm install
  
  
services:
  - mysql

script:
  - mysqldump -uroot -p='' pixagram < pixagram_testdb.sql
  - npm test
   

