language: node_js
install:
  - nvm install node
  - node -v
  - npm install --save-dev jest
  - npm install supertest
  - npm install
  
  
services:
  - mysql

script:
  - mysqldump -uroot -p='' pixagram < pixagram_testdb.sql
  - npm test
   

